### ISSUE TITLE
creating a contract with a nested index "details.message" throws an error

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dpp#186]
Using a valid contract with toplevel index ( [view on dpp](http://console.dashevo.io/#/platform/ECWtEzkF7vze16KwtEZgkHLiiaYDKqd9PQ8z1e1cXLCq?showcontract=true) ) and changing the index to access the nested property `"details.message"`

```
{
  "note": {
    "indices": [
      {
        "properties": [
          {
            "details.message": "asc"
          }
        ]
      }
    ],
    "required": [
      "details"
    ],
    "properties": {
      "details": {
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "additionalProperties": false
  }
}
```

throws error `'details.message' property is not defined in the document`

**Comment by shumkov** [comment]
@dashameter the link doesn't work anymore. We have such use case in DPNS and it works. Please take a look https://github.com/dashevo/dpns-contract/blob/v0.2-dev/src/schema/dpns-documents.json#L16-L19

**Comment by dashameter** [comment]
`     "type": "object",` was missing, this works now:

```
{
 "$id": "VYfJMya4E94QFLZLYtV7saG2nE3Z5BohJ9PFu7HWm7y",
 "$schema": "https://schema.dash.org/dpp-0-4-0/meta/data-contract",
 "ownerId": "5aAinbP9UKXdWTyywW9C7Qk6u8WbkKDg4gNzYZbhTqfr",
 "documents": {
  "note": {
   "indices": [
    {
     "properties": [
      {
       "details.message": "asc"
      }
     ]
    }
   ],
   "properties": {
    "details": {
     "type": "object",
     "properties": {
      "message": {
       "type": "string"
      }
     },
     "additionalProperties": false
    }
   },
   "additionalProperties": false
  }
 }
}
```

[http://console.dashevo.io/#/platform/VYfJMya4E94QFLZLYtV7saG2nE3Z5BohJ9PFu7HWm7y](http://console.dashevo.io/#/platform/VYfJMya4E94QFLZLYtV7saG2nE3Z5BohJ9PFu7HWm7y)

**Comment by shumkov** [comment]
It should work without the `type` keyword. it’s an object by default. Please reopen the issue.

**Comment by dashameter** [comment]
@shumkov should this still work without `type: object` or is the type declaration enforced now and we can closed the issue?

**Comment by shumkov** [comment]
Nope, in v0.20 we introduced strict validation rules, so `type` must be always defined.

**Comment by dashameter** [comment]
@shumkov if `type` must be defined, this issue can be closed now ?!

**Comment by SamKirby22** [comment]
Agreed on triage to close.
