### ISSUE TITLE
registering identity throws error "invalid ST" missing metadata information

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dpp#292]
Registering an identity from a browser on testnet throws:

```
code: 3
message: "State Transition is invalid"
metadata: Object
content-length: "0"
content-type: "application/grpc-web-text+proto"
grpc-message: "State Transition is invalid"
grpc-status: "3"
```

Missing additional metadata on the error object making it hard to debug what causes the State Transition to fail.

Discussion:
https://discord.com/channels/670271785974890526/670599939528851476/795526039883087913

https://discord.com/channels/670271785974890526/670599939528851476/795627749888098334

**Comment by akay777** [comment]
Did this issue get resolved?

**Comment by dashameter** [comment]
This should be fixed in v.20, closing for now
