### ISSUE TITLE
TypeError: aDocument.getOwnerId is not a function

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dpp#305]
upon submitting a contactRequest document I get the error `  <rejected> TypeError: aDocument.getOwnerId is not a function`, submitting the note example from the tutorial works fine ..

```
contactRequestDocument.toJSON() :>>  {
  '$protocolVersion': 0,
  '$id': 'Bj3pEGd7VJWkPfbdwtgCEZNjwdf6xKCLfJ19xRCecGBe',
  '$type': 'contactRequest',
  '$dataContractId': '2DAncD4YTjfhSQZYrsQ659xbM7M5dNEkyfBEAg9SsS3W',
  '$ownerId': 'Dxp5EpkcU3jpHL3e6UgUsYgukNFwjnpCPXETLFEC2F2R',
  '$revision': 1,
  toUserId: '7Lpfy94eLFajB5qRTc355Lrx2BANAynEjb5okHTvV1BC',
  senderKeyIndex: 0,
  accountReference: 75057716,
  recipientKeyIndex: 0,
  encryptedPublicKey: 'jEQRF0BjbE/cUJYj/hvT4Ca2Gi6uAKFCqqpR/z3aNNQBXW78xW0w1VBRr5wNBD+TppYH9lFNWV9iiMdGlkfy8AUhMiwHuNhLejLXJ4hNaQd1mIOuxTXb2TKS/v6ci/l8',
  encryptedAccountLabel: 'WEHifbkLBSMdaZF9iya4r5pbp+bZlED5fn5CXYowIaS9oze5fL3Jujj+nPSE/H1B',
  '$createdAt': 1619865645729
}
```

```
result :>>  Promise {
  <rejected> TypeError: aDocument.getOwnerId is not a function
      at DocumentFactory.createStateTransition (node_modules/dash/node_modules/@dashevo/dpp/lib/document/DocumentFactory.js:207:31)
      at DocumentFacade.createStateTransition (node_modules/dash/node_modules/@dashevo/dpp/lib/document/DocumentFacade.js:99:25)
      at Platform.<anonymous> (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:61:61)
      at step (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:33:23)
      at Object.next (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:14:53)
      at node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:4:12)
      at Platform.broadcast (node_modules/dash/build/src/SDK/Client/Platform/methods/documents/broadcast.js:55:12)
}
```

**Comment by dashameter** [comment]
retest depends on testnet IP whitelist @dash-maverick @SamKirby22

**Comment by dash-maverick** [comment]
IPs that are known to work
`34.219.81.129
34.221.42.205
34.208.88.128
54.189.162.193
34.220.124.90
54.201.242.241
54.68.10.46
34.210.81.39
18.237.47.243
54.187.229.6
34.214.102.160
34.219.93.145
35.165.37.186
54.202.157.120
34.215.144.176
52.13.119.69
34.220.12.188
18.237.5.33
54.191.32.70
54.213.219.155
35.167.25.157`

However the `502 Bad Gateway` issue https://github.com/dashevo/js-dash-sdk/issues/298 has been resolved (showing a different problem but maybe not an issue for this case), so maybe the retest could be normally performed?

**Comment by dashameter** [comment]
failed retest:
```
Something went wrong:
 TypeError: aDocument.getOwnerId is not a function
 ```

**Comment by dash-maverick** [comment]
registered that in our backlog

**Comment by SamKirby22** [comment]
As per triage call, this impacts our ability to use send contact request via DashPay Wallet and should be considered our highest priority for fixing.

**Comment by jawid-h** [comment]
Hey @dashameter , in your script you're using following code:
 ```
const documentBatch = {
    create: [contactRequest], // Document(s) to create
    replace: [], // Document(s) to update
    delete: [], // Document(s) to delete
  };
```
But you're sending the JSON instead of a Document instance you've created earlier called _contactRequestDocument_ . If you change that to:
```
 const documentBatch = {
    create: [contactRequestDocument], // Document(s) to create
    replace: [], // Document(s) to update
    delete: [], // Document(s) to delete
  };
```
that should work as expected.

**Comment by dashameter** [comment]
thanks @jawid-h first contactRequest successfully sent from javascript wallet to android wallet:

![c-dashpayjs](https://user-images.githubusercontent.com/57665975/145575405-bd5a48b5-7767-46d5-bdd4-88ace342f3b6.png)

**Comment by dash-maverick** [comment]
Awesome Guys :)
