### ISSUE TITLE
Creating "Identity" with DashJS SDK throws an "InvalidResponseError"

### ISSUE THREAD

**Issue by mayoreee** [dashevo/js-dpp#328]
Using the Dash JS SDK in creating a new `identity` throws an `InvalidResponseError`, but Identity finally gets created after multiple retries.

## Expected Behavior
Successfully creates a new `identity`

## Current Behavior

Throws error: `InvalidResponseError: Invalid response: Metadata is not defined`

Multiple retries finally creates an `identity

## Steps to Reproduce (for bugs)

````js
const Dash = require('dash')
const clientOpts = {
  network: 'testnet',
  wallet: {
    mnemonic: 'ask illness knife cash occur science cloud lecture episode shift moment upgrade',
    unsafeOptions: {
      skipSynchronizationBeforeHeight: 415000, // only sync from start of 2021
    },
  },
};
const client = new Dash.Client(clientOpts);

const createIdentity = async () => {
  return client.platform.identities.register();
};

createIdentity()
  .then((d) => console.log('Identity:\n', d.toJSON()))
  .catch((e) => console.error('Something went wrong:\n', e))
  .finally(() => client.disconnect());
````
## Your Environment
* dash @3.20.1
* node @16.5.0

**Comment by shumkov** [comment]
This is happening because some of the nodes still not updated to v0.20 and we don't have PoSe that supposes to ban them atm. We are working on a workaround.

**Comment by dashameter** [comment]
@shumkov @mayoreee is this issue resolved and can be closed or shall we size and prioritize it ?

**Comment by shumkov** [comment]
I guess so. @mayoreee ?

**Comment by dashameter** [comment]
passed retest, please close @SamKirby22

**Comment by SamKirby22** [comment]
Thanks. Triage sheet updated and issue closed.
